### ISSUE TITLE
`date` gem failed to load

### ISSUE THREAD

**Issue by ntkme** [oneclick/rubyinstaller2-packages#25]
@larskanis So after trying the updated head-arm package, it's no longer crashing at `ruby --version`, but now it crashes on loading the `date` gem.

```
 <internal:C:/rubyinstaller-head-arm/lib/ruby/3.5.0+0/rubygems/core_ext/kernel_require.rb>:136:in 'Kernel#require': 126: The specified module could not be found.   - C:/rubyinstaller-head-arm/lib/ruby/3.5.0+0/aarch64-mingw-ucrt/date_core.so (LoadError)
```

**Comment by ntkme** [comment]
Here is a reproduction on GitHub Actions:

``` yaml
on:
  push:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-11-arm]
        ruby-version: [ruby, head]
        windows-toolchain: [default, none]
    steps:
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          windows-toolchain: ${{ matrix.windows-toolchain }}
          bundler: none

      - run: ruby -r date -e exit
        shell: bash
```
